name: timer_bloc
description: Timer Bloc Project

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  bloc: ^6.1.3
  flutter_bloc: ^6.1.3
  equatable: ^2.0.0
  wave: ^0.1.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
